############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Meetup.com"
url = "https://meetup.com/devops-kansas-city"
weight = 3

[[main]]
weight = 4
name = "DevOpsDays KC"
url = "https://devopsdayskc.org"

[[main]]
name = "Sponsor Us"
url = "/sponsor"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Sponsor Us"
url = "/sponsor"
weight = 2

[[footer]]
name = "Contact Us"
url = "/contact"
weight = 3
