######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://example.org"
title = "The DevOps KC Community"
theme = "hugoplate"
timeZone = "America/Chicago"
summaryLength = 25 # post excerpt, see https://gohugo.io/content-management/excerpts/
# disableLanguages = [ ] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
defaultContentLanguage = 'en'   # default language
defaultContentLanguageInSubdir = false  # needs to be true if you want to use the language code as a subdirectory and language specific 404 page
